apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  publishNotReadyAddresses: true
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
    name: client
  - port: {{ .Values.service.gossipPort }}
    targetPort: {{ .Values.service.gossipPort }}
    name: gossip
  clusterIP: None
  selector:
    app: {{ .Release.Name }}
